### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by filipwasil** [filipwasil/fillwave#71]
#0  0x00007ffff78457a3 in fillwave::core::VertexArray::bind(unsigned int) () from /home/filip/Projects/fillwave_build/libfillwave.so
#1  0x00007ffff78831fa in fillwave::framework::Mesh::initVAO() () from /home/filip/Projects/fillwave_build/libfillwave.so
#2  0x00007ffff7880984 in fillwave::framework::Mesh::Mesh(fillwave::Engine_, fillwave::framework::Material const&, std::shared_ptrfillwave::core::TextureRegion, std::shared_ptrfillwave::core::TextureRegion, std::shared_ptrfillwave::core::TextureRegion, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::framework::LightSystem_, std::shared_ptrfillwave::core::VertexBufferBasic, std::shared_ptrfillwave::core::IndexBufferBasic, fillwave::framework::Animator*, unsigned int) () from /home/filip/Projects/fillwave_build/libfillwave.so
#3  0x00007ffff787fb07 in void __gnu_cxx::new_allocatorfillwave::framework::Mesh::construct<fillwave::framework::Mesh, fillwave::Engine*&, fillwave::framework::Material, std::shared_ptr<fillwave::core::TextureRegion>, std::shared_ptrfillwave::core::TextureRegion, std::shared_ptrfillwave::core::TextureRegion, fillwave::core::Program_&, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::framework::LightSystem_, std::shared_ptrfillwave::core::VertexBufferBasic, std::shared_ptrfillwave::core::IndexBufferBasic >(fillwave::framework::Mesh_, fillwave::Engine_&, fillwave::framework::Material&&, std::shared_ptrfillwave::core::TextureRegion&&, std::shared_ptrfillwave::core::TextureRegion&&, std::shared_ptrfillwave::core::TextureRegion&&, fillwave::core::Program_&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::framework::LightSystem_&&, std::shared_ptrfillwave::core::VertexBufferBasic&&, std::shared_ptrfillwave::core::IndexBufferBasic&&) () from /home/filip/Projects/fillwave_build/libfillwave.so
#4  0x00007ffff787f5bc in std::enable_ifstd::__and_<std::allocator_traits<std::allocator<fillwave::framework::Mesh >::__construct_helper<fillwave::framework::Mesh, fillwave::Engine*&, fillwave::framework::Material, std::shared_ptr<fillwave::core::TextureRegion>, std::shared_ptrfillwave::core::TextureRegion, std::shared_ptrfillwave::core::TextureRegion, fillwave::core::Program_&, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::framework::LightSystem_, std::shared_ptrfillwave::core::VertexBufferBasic, std::shared_ptrfillwave::core::IndexBufferBasic >::type>::value, void>::type std::allocator_traitsstd::allocator<fillwave::framework::Mesh >::_S_construct<fillwave::framework::Mesh, fillwave::Engine_&, fillwave::framework::Material, std::shared_ptrfillwave::core::TextureRegion, std::shared_ptrfillwave::core::TextureRegion, std::shared_ptrfillwave::core::TextureRegion, fillwave::core::Program_&, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::framework::LightSystem_, std::shared_ptrfillwave::core::VertexBufferBasic, std::shared_ptrfillwave::core::IndexBufferBasic >(std::allocatorfillwave::framework::Mesh&, fillwave::framework::Mesh_, fillwave::Engine_&, fillwave::framework::Material&&, std::shared_ptrfillwave::core::TextureRegion&&, std::shared_ptrfillwave::core::TextureRegion&&, std::shared_ptrfillwave::core::TextureRegion&&, fillwave::core::Program_&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::framework::LightSystem_&&, std::shared_ptrfillwave::core::VertexBufferBasic&&, std::shared_ptrfillwave::core::IndexBufferBasic&&) () from /home/filip/Projects/fillwave_build/libfillwave.so
#5  0x00007ffff787f0ae in decltype (_S_construct({parm#1}, {parm#2}, (forwardfillwave::Engine*&)({parm#3}), (forwardfillwave::framework::Material)({parm#3}), (forwardstd::shared_ptr<fillwave::core::TextureRegion >)({parm#3}), (forwardstd::shared_ptr<fillwave::core::TextureRegion >)({parm#3}), (forwardstd::shared_ptr<fillwave::core::TextureRegion >)({parm#3}), (forwardfillwave::core::Program*&)({parm#3}), (forwardfillwave::core::Program*)({parm#3}), (forwardfillwave::core::Program*)({parm#3}), (forwardfillwave::core::Program*)({parm#3}), (forwardfillwave::core::Program*)({parm#3}), (forwardfillwave::core::Program*)({parm#3}), (forwardfillwave::framework::LightSystem*)({parm#3}), (forwardstd::shared_ptr<fillwave::core::VertexBufferBasic >)({parm#3}), (forwardstd::shared_ptr<fillwave::core::IndexBufferBasic >)({parm#3}))) std::allocator_traitsstd::allocator<fillwave::framework::Mesh >::construct<fillwave::framework::Mesh, fillwave::Engine*&, fillwave::framework::Material, std::shared_ptr<fillwave::core::TextureRegion>, std::shared_ptrfillwave::core::TextureRegion, std::shared_ptrfillwave::core::TextureRegion, fillwave::core::Program_&, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::framework::LightSystem_, std::shared_ptrfillwave::core::VertexBufferBasic, std::shared_ptrfillwave::core::IndexBufferBasic >(std::allocatorfillwave::framework::Mesh&, fillwave::framework::Mesh_, fillwave::Engine_&, fillwave::framework::Material&&, std::shared_ptrfillwave::core::TextureRegion&&, std::shared_ptrfillwave::core::TextureRegion&&, std::shared_ptrfillwave::core::TextureRegion&&, fillwave::core::Program_&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::framework::LightSystem_&&, std::shared_ptrfillwave::core::VertexBufferBasic&&, std::shared_ptrfillwave::core::IndexBufferBasic&&) () from /home/filip/Projects/fillwave_build/libfillwave.so
#6  0x00007ffff787e9cf in std::_Sp_counted_ptr_inplace<fillwave::framework::Mesh, std::allocator<fillwave::framework::Mesh>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<fillwave::Engine*&, fillwave::framework::Material, std::shared_ptr<fillwave::core::TextureRegion>, std::shared_ptrfillwave::core::TextureRegion, std::shared_ptrfillwave::core::TextureRegion, fillwave::core::Program_&, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::framework::LightSystem_, std::shared_ptrfillwave::core::VertexBufferBasic, std::shared_ptrfillwave::core::IndexBufferBasic >(std::allocatorfillwave::framework::Mesh, fillwave::Engine_&, fillwave::framework::Material&&, std::shared_ptrfillwave::core::TextureRegion&&, std::shared_ptrfillwave::core::TextureRegion&&, std::shared_ptr---Type <return> to continue, or q <return> to quit---

fillwave::core::TextureRegion&&, fillwave::core::Program_&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::framework::LightSystem*&&, std::shared_ptrfillwave::core::VertexBufferBasic&&, std::shared_ptrfillwave::core::IndexBufferBasic&&) ()
   from /home/filip/Projects/fillwave_build/libfillwave.so
#7  0x00007ffff787df73 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<fillwave::framework::Mesh, std::allocator<fillwave::framework::Mesh>, fillwave::Engine_&, fillwave::framework::Material, std::shared_ptrfillwave::core::TextureRegion, std::shared_ptrfillwave::core::TextureRegion, std::shared_ptrfillwave::core::TextureRegion, fillwave::core::Program_&, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::framework::LightSystem_, std::shared_ptrfillwave::core::VertexBufferBasic, std::shared_ptrfillwave::core::IndexBufferBasic >(std::_Sp_make_shared_tag, fillwave::framework::Mesh_, std::allocatorfillwave::framework::Mesh const&, fillwave::Engine_&, fillwave::framework::Material&&, std::shared_ptrfillwave::core::TextureRegion&&, std::shared_ptrfillwave::core::TextureRegion&&, std::shared_ptrfillwave::core::TextureRegion&&, fillwave::core::Program_&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::framework::LightSystem*&&, std::shared_ptrfillwave::core::VertexBufferBasic&&, std::shared_ptrfillwave::core::IndexBufferBasic&&) () from /home/filip/Projects/fillwave_build/libfillwave.so
#8  0x00007ffff787d64e in std::__shared_ptr<fillwave::framework::Mesh, (__gnu_cxx::_Lock_policy)2>::__shared_ptrstd::allocator<fillwave::framework::Mesh, fillwave::Engine_&, fillwave::framework::Material, std::shared_ptrfillwave::core::TextureRegion, std::shared_ptrfillwave::core::TextureRegion, std::shared_ptrfillwave::core::TextureRegion, fillwave::core::Program_&, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::framework::LightSystem_, std::shared_ptrfillwave::core::VertexBufferBasic, std::shared_ptrfillwave::core::IndexBufferBasic >(std::_Sp_make_shared_tag, std::allocatorfillwave::framework::Mesh const&, fillwave::Engine_&, fillwave::framework::Material&&, std::shared_ptrfillwave::core::TextureRegion&&, std::shared_ptrfillwave::core::TextureRegion&&, std::shared_ptrfillwave::core::TextureRegion&&, fillwave::core::Program_&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::framework::LightSystem_&&, std::shared_ptrfillwave::core::VertexBufferBasic&&, std::shared_ptrfillwave::core::IndexBufferBasic&&) () from /home/filip/Projects/fillwave_build/libfillwave.so
#9  0x00007ffff787d07c in std::shared_ptrfillwave::framework::Mesh::shared_ptrstd::allocator<fillwave::framework::Mesh, fillwave::Engine_&, fillwave::framework::Material, std::shared_ptrfillwave::core::TextureRegion, std::shared_ptrfillwave::core::TextureRegion, std::shared_ptrfillwave::core::TextureRegion, fillwave::core::Program_&, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::framework::LightSystem_, std::shared_ptrfillwave::core::VertexBufferBasic, std::shared_ptrfillwave::core::IndexBufferBasic >(std::_Sp_make_shared_tag, std::allocatorfillwave::framework::Mesh const&, fillwave::Engine_&, fillwave::framework::Material&&, std::shared_ptrfillwave::core::TextureRegion&&, std::shared_ptrfillwave::core::TextureRegion&&, std::shared_ptrfillwave::core::TextureRegion&&, fillwave::core::Program_&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::framework::LightSystem_&&, std::shared_ptrfillwave::core::VertexBufferBasic&&, std::shared_ptrfillwave::core::IndexBufferBasic&&) ()

   from /home/filip/Projects/fillwave_build/libfillwave.so
#10 0x00007ffff787cbce in std::shared_ptrfillwave::framework::Mesh std::allocate_shared<fillwave::framework::Mesh, std::allocator<fillwave::framework::Mesh>, fillwave::Engine_&, fillwave::framework::Material, std::shared_ptrfillwave::core::TextureRegion, std::shared_ptrfillwave::core::TextureRegion, std::shared_ptrfillwave::core::TextureRegion, fillwave::core::Program_&, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::framework::LightSystem_, std::shared_ptrfillwave::core::VertexBufferBasic, std::shared_ptrfillwave::core::IndexBufferBasic >(std::allocatorfillwave::framework::Mesh const&, fillwave::Engine_&, fillwave::framework::Material&&, std::shared_ptrfillwave::core::TextureRegion&&, std::shared_ptrfillwave::core::TextureRegion&&, std::shared_ptrfillwave::core::TextureRegion&&, fillwave::core::Program_&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::framework::LightSystem_&&, std::shared_ptrfillwave::core::VertexBufferBasic&&, std::shared_ptrfillwave::core::IndexBufferBasic&&) ()

   from /home/filip/Projects/fillwave_build/libfillwave.so
#11 0x00007ffff787c4b1 in std::shared_ptrfillwave::framework::Mesh std::make_shared<fillwave::framework::Mesh, fillwave::Engine*&, fillwave::framework::Material, std::shared_ptr<fillwave::core::TextureRegion>, std::shared_ptrfillwave::core::TextureRegion, std::shared_ptrfillwave::core::TextureRegion, fillwave::core::Program_&, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::core::Program_, fillwave::framework::LightSystem_, std::shared_ptrfillwave::core::VertexBufferBasic, std::shared_ptrfillwave::core::IndexBufferBasic >(fillwave::Engine_&, fillwave::framework::Material&&, std::shared_ptrfillwave::core::TextureRegion&&, std::shared_ptrfillwave::core::TextureRegion&&, std::shared_ptrfillwave::core::TextureRegion&&, fillwave::core::Program_&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::core::Program_&&, fillwave::framework::LightSystem*&&, std::shared_ptr<fillwave::core::VertexBufferB---Type <return> to continue, or q <return> to quit---

asic>&&, std::shared_ptrfillwave::core::IndexBufferBasic&&) () from /home/filip/Projects/fillwave_build/libfillwave.so
#12 0x00007ffff787aca3 in fillwave::framework::MeshTerrain::MeshTerrain(fillwave::Engine_, fillwave::core::Program_, fillwave::framework::TerrainConstructor*, fillwave::framework::Material const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int) ()

   from /home/filip/Projects/fillwave_build/libfillwave.so
#13 0x00000000004205d9 in __gnu_cxx::new_allocatorfillwave::framework::MeshTerrain::construct<fillwave::framework::MeshTerrain, fillwave::Engine*&, fillwave::core::Program*&, fillwave::framework::MountainConstructor*, fillwave::framework::Material&, char const (&) [18], char const (&) [24], char const (&) [1], int, int>(fillwave::framework::MeshTerrain_, fillwave::Engine_&, fillwave::core::Program_&, fillwave::framework::MountainConstructor_&&, fillwave::framework::Material&, char const (&) [18], char const (&) [24], char const (&) [1], int&&, int&&) (this=0x7fffffffd887, __p=0xee3ad0) at /usr/include/c++/5/ext/new_allocator.h:120
#14 0x00000000004202d3 in std::allocator_traitsstd::allocator<fillwave::framework::MeshTerrain >::_S_construct<fillwave::framework::MeshTerrain, fillwave::Engine*&, fillwave::core::Program*&, fillwave::framework::MountainConstructor*, fillwave::framework::Material&, char const (&) [18], char const (&) [24], char const (&) [1], int, int>(std::allocatorfillwave::framework::MeshTerrain&, fillwave::framework::MeshTerrain_, fillwave::Engine_&, fillwave::core::Program_&, fillwave::framework::MountainConstructor_&&, fillwave::framework::Material&, char const (&) [18], char const (&) [24], char const (&) [1], int&&, int&&) (__a=..., __p=0xee3ad0) at /usr/include/c++/5/bits/alloc_traits.h:256
#15 0x000000000041ff9f in std::allocator_traitsstd::allocator<fillwave::framework::MeshTerrain >::construct<fillwave::framework::MeshTerrain, fillwave::Engine*&, fillwave::core::Program*&, fillwave::framework::MountainConstructor*, fillwave::framework::Material&, char const (&) [18], char const (&) [24], char const (&) [1], int, int>(std::allocatorfillwave::framework::MeshTerrain&, fillwave::framework::MeshTerrain_, fillwave::Engine_&, fillwave::core::Program_&, fillwave::framework::MountainConstructor_&&, fillwave::framework::Material&, char const (&) [18], char const (&) [24], char const (&) [1], int&&, int&&) (__a=..., __p=0xee3ad0) at /usr/include/c++/5/bits/alloc_traits.h:402
#16 0x000000000041fb84 in std::_Sp_counted_ptr_inplace<fillwave::framework::MeshTerrain, std::allocator<fillwave::framework::MeshTerrain>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<fillwave::Engine*&, fillwave::core::Program*&, fillwave::framework::MountainConstructor*, fillwave::framework::Material&, char const (&) [18], char const (&) [24], char const (&) [1], int, int>(std::allocatorfillwave::framework::MeshTerrain, fillwave::Engine_&, fillwave::core::Program_&, fillwave::framework::MountainConstructor*&&, fillwave::framework::Material&, char const (&) [18], char const (&) [24], char const (&) [1], int&&, int&&) (this=0xee3ac0, __a=...)

```
at /usr/include/c++/5/bits/shared_ptr_base.h:522
```
#17 0x000000000041f53f in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<fillwave::framework::MeshTerrain, std::allocator<fillwave::framework::MeshTerrain>, fillwave::Engine_&, fillwave::core::Program_&, fillwave::framework::MountainConstructor_, fillwave::framework::Material&, char const (&) [18], char const (&) [24], char const (&) [1], int, int>(std::_Sp_make_shared_tag, fillwave::framework::MeshTerrain_, std::allocatorfillwave::framework::MeshTerrain const&, fillwave::Engine_&, fillwave::core::Program_&, fillwave::framework::MountainConstructor*&&, fillwave::framework::Material&, char const (&) [18], char const (&) [24], char const (&) [1], int&&, int&&) (

```
this=0x7fffffffdcd8, __a=...) at /usr/include/c++/5/bits/shared_ptr_base.h:617
```
#18 0x000000000041efa4 in std::__shared_ptr<fillwave::framework::MeshTerrain, (__gnu_cxx::_Lock_policy)2>::__shared_ptrstd::allocator<fillwave::framework::MeshTerrain, fillwave::Engine_&, fillwave::core::Program_&, fillwave::framework::MountainConstructor_, fillwave::framework::Material&, char const (&) [18], char const (&) [24], char const (&) [1], int, int>(std::_Sp_make_shared_tag, std::allocatorfillwave::framework::MeshTerrain const&, fillwave::Engine_&, fillwave::core::Program_&, fillwave::framework::MountainConstructor_&&, fillwave::framework::Material&, char const (&) [18], char const (&) [24], char const (&) [1], int&&, int&&) (this=0x7fffffffdcd0, __tag=..., __a=...)

```
at /usr/include/c++/5/bits/shared_ptr_base.h:1097
```
#19 0x000000000041e9a3 in std::shared_ptrfillwave::framework::MeshTerrain::shared_ptrstd::allocator<fillwave::framework::MeshTerrain, fillwave::Engine_&, fillwave::core::Program_&, fillwave::framework::MountainConstructor_, fillwave::framework::Material&, char const (&) [18], char const (&) [24], char const (&) [1], int, int>(std::_Sp_make_shared_tag, std::allocatorfillwave::framework::MeshTerrain const&, fillwave::Engine_&, fillwave::core::Program_&, fillwave::framework::MountainConstructor_&&, fillwave::framework::Material&, char const (&) [18], char const (&) [24], char const (&) [1], int&&, int&&) (this=0x7fffffffdcd0, __tag=..., __a=...) at /usr/include/c++/5/bits/shared_ptr.h:319
#20 0x000000000041e3d7 in std::allocate_shared<fillwave::framework::MeshTerrain, std::allocator<fillwave::framework::MeshTerrain>, fillwave::Engine_&, fillwave::core::Program_&, fillwave::framework::MountainConstructor_, fillwave::framework::Material&, char const (&) [18], char const (&) [24], char const (&) [1], int, int>(std::allocatorfillwave::framework::MeshTerrain const&, fillwave::Engine_&, fillwave::core::Program_&, fillwave::framework::MountainConstructor_&&, fillwave::framework::Material&, char const (&) [18], char const (&) [24], char const (&) [1], int&&, int&&) (__a=...) at /usr/include/c++/5/bits/shared_ptr.h:614
#21 0x000000000041dd2b in std::make_shared<fillwave::framework::MeshTerrain, fillwave::Engine*&, fillwave::core::Program*&, fillwave::framework::MountainConstructor*, fillwave:---Type <return> to continue, or q <return> to quit---

:framework::Material&, char const (&) [18], char const (&) [24], char const (&) [1], int, int>(fillwave::Engine_&, fillwave::core::Program_&, fillwave::framework::MountainConstructor*&&, fillwave::framework::Material&, char const (&) [18], char const (&) [24], char const (&) [1], int&&, int&&) () at /usr/include/c++/5/bits/shared_ptr.h:630
#22 0x000000000041c5bc in perform () at /home/filip/Projects/fillwave/examples/linux/src/test.cpp:103
#23 0x000000000041bdbf in main (argc=1, argv=0x7fffffffdea8) at /home/filip/Projects/fillwave/examples/linux/src/test.cpp:47

**Comment by filipwasil** [comment]
Manager overflow. Fix in review.
