### ISSUE TITLE
Problem with examples

### ISSUE THREAD

**Issue by filipwasil** [filipwasil/fillwave#75]
Crash when loading mesh from model.

**Comment by filipwasil** [comment]
On example fails to run

**Comment by filipwasil** [comment]
Examples failing right now:

particles

0  0x00007ffff6a0b267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007ffff6a0ceca in __GI_abort () at abort.c:89
#2  0x00007ffff7a71cd9 in fillwave::core::Uniform::push(int, int) () from /usr/lib/libfillwave.so
#3  0x00007ffff7a71d2d in fillwave::core::Uniform::push(int, unsigned int) () from /usr/lib/libfillwave.so
#4  0x00007ffff7a9962c in fillwave::framework::EmiterPointGPU::draw(fillwave::framework::ICamera&) () from /usr/lib/libfillwave.so
#5  0x00007ffff7b1ce62 in fillwave::framework::RendererFR::draw(fillwave::framework::ICamera&) () from /usr/lib/libfillwave.so
#6  0x00007ffff7accec5 in fillwave::framework::ScenePerspective::draw() () from /usr/lib/libfillwave.so
#7  0x00007ffff7a22b46 in fillwave::Engine::EngineImpl::drawSceneCore() () from /usr/lib/libfillwave.so
#8  0x00007ffff7a22ace in fillwave::Engine::EngineImpl::drawScene(float) () from /usr/lib/libfillwave.so
#9  0x00007ffff7a186ac in fillwave::Engine::EngineImpl::draw(float) () from /usr/lib/libfillwave.so
#10 0x00007ffff7a192f9 in fillwave::Engine::draw(float) () from /usr/lib/libfillwave.so
#11 0x000000000041cb64 in ContextGLFW::render (this=0x7fffffffdd80) at /home/filip/Projects/fillwave-examples/src/ContextGLFW.cpp:98
#12 0x00000000004152b3 in main (argc=1, argv=0x7fffffffde98) at /home/filip/Projects/fillwave-examples/src/example_particles/example_particles.cpp:42

**Comment by filipwasil** [comment]
Failing because of old fashioned manager structure.

Work in progress.
